parameters:
  name: ''
  displayName: ''
  pool: ''
  apiKey: ''
  apiVersion: ''
  apiUrl: ''
  os: ''
  depends: ''
  moduleName: ''
  artifactsPAT: ''
  artifactsUrl: ''
  pwsh: true

jobs:
  - deployment: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    variables:
      BURPSUITE_APIKEY: ${{ parameters.apiKey }}
      BURPSUITE_APIVERSION: ${{ parameters.apiVerion }}
      BURPSUITE_URL: ${{ parameters.apiUrl }}
      BURPSUITE_MODULENAME: ${{ parameters.moduleName }}
      ARTIFACTS_PAT: ${{ parameters.artifactsPAT }}
      ARTIFACTS_URL: ${{ parameters.artifactsUrl }}
    ${{ if eq(parameters['depends'], true) }}:
    dependsOn: ${{ parameters.depends }}
    pool:
      vmImage: ${{ parameters.pool }}
    environment: '${{ parameters.displayName }}'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: PowerShell@2
              displayName: 'Register Private Repository'
              inputs:
                targetType: 'inline'
                script: |
                  $n = $Env:BURPSUITE_MODULENAME
                  $e = "example@example.org"
                  $url = $Env:ARTIFACTS_URL
                  $pwd = ConvertTo-SecureString $Env:ARTIFACTSPAT -AsPlainText -Force
                  $creds = New-Object PSCredential($e, $pwd)

                  # LINK: https://github.com/Microsoft/artifacts-credprovider
                  $Env:NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED = 'true'
                  $Env:VSS_NUGET_EXTERNAL_FEED_ENDPOINTS = '{{"endpointCredentials": [{{"endpoint":"{0}", "username":"{1}", "password":"{2}"}}]}}' -f $url, $e, $pwd

                  if(-not (Get-PSRepository | ? Name -eq $n)) { Register-PSRepository -Credential $creds -Name $n -SourceLocation $url -PublishLocation $url -InstallationPolicy Trusted -Verbose }
                env:
                  ARTIFACTSPAT: $(ARTIFACTS_PAT)
                pwsh: ${{ parameters.pwsh }}

            - task: PowerShell@2
              displayName: 'Install $(BURPSUITE_MODULENAME) Module'
              inputs:
                targetType: 'inline'
                script: |
                  # Load the psd1 file so you can read the version
                  $manifest = Split-Path -Path (Resolve-Path -Path "$(Pipeline.Workspace)/module/$($Env:BURPSUITE_MODULENAME)/*/*.psd1")

                  $n = $Env:BURPSUITE_MODULENAME
                  $e = "example@example.org"
                  $b = "$($manifest.ModuleVersion).$(Build.BuildId)"
                  $pwd = ConvertTo-SecureString $Env:ARTIFACTSPAT -AsPlainText -Force # Readonly PAT for Azure DevOps artifacts
                  $creds = New-Object PSCredential($e, $pwd)

                  # LINK: https://github.com/Microsoft/artifacts-credprovider
                  $Env:NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED = 'true'
                  $Env:VSS_NUGET_EXTERNAL_FEED_ENDPOINTS = '{{"endpointCredentials": [{{"endpoint":"{0}", "username":"{1}", "password":"{2}"}}]}}' -f $url, $e, $pwd

                  Install-Module -Name $Env:BURPSUITE_MODULENAME -Repository $n -Credential $creds -MaximumVersion $b -MinimumVersion $b -Force -Scope CurrentUser -Verbose
                workingDirectory: '$(Pipeline.Workspace)/test'
                env:
                  ARTIFACTSPAT: $(ARTIFACTS_PAT)
                pwsh: ${{ parameters.pwsh }}

            - task: PowerShell@2
              displayName: 'Install Pester'
              inputs:
                targetType: 'inline'
                script: 'Install-Module -Name Pester -Repository PSGallery -Force -Scope CurrentUser -AllowClobber -SkipPublisherCheck'
                pwsh: ${{ parameters.pwsh }}

            - task: PowerShell@2
              displayName: 'Run Integration Tests'
              inputs:
                targetType: 'inline'
                script: |
                  $env:BURPSUITE_URL = $env:BURPSUITE_URL
                  $env:BURPSUITE_APIKEY = $env:BURPSUITE_APIKEY
                  $env:BURPSUITE_APIVERSION = $env:BURPSUITE_APIVERSION

                  Import-Module $Env:BURPSUITE_MODULENAME
                  if (-not (Get-Module -Name Pester)) { Import-Module -Name Pester -ErrorAction Stop }

                  $PesterPreference = [PesterConfiguration]::Default
                  $PesterPreference.Run.PassThru = $true
                  $PesterPreference.TestResult.Enabled = $true
                  $PesterPreference.TestResult.OutputPath = Join-Path -Path "$(Pipeline.Workspace)/test/integration" -ChildPath "$($Env:BURPSUITE_MODULENAME)-TestsResults.xml"

                  $testResults = Invoke-Pester -Configuration $PesterPreference
                  Write-Host 'Pester results:' -ForegroundColor Yellow
                  $tableProperties = 'Result', 'FailedCount', 'FailedBlocksCount', 'FailedContainersCount', 'PassedCount', 'SkippedCount', 'NotRunCount', 'TotalCount', 'Duration'
                  $testResults | Format-Table -AutoSize -Property $tableProperties

                  if ($testResults.FailedCount -gt 0) { throw 'One or more Pester tests failed' }
                failOnStderr: true
                workingDirectory: '$(Pipeline.Workspace)/test/integration'
                env:
                  BURPSUITE_APIKEY: $(BURPSUITE_APIKEY)
                pwsh: ${{ parameters.pwsh }}

            - task: PublishTestResults@2
              displayName: 'Publish Test Results'
              inputs:
                testResultsFormat: NUnit
                testResultsFiles: '**/test-results.xml'
                searchFolder: '$(Pipeline.Workspace)/test/integration'
                testRunTitle: '${{ parameters.os }} Tests'
              continueOnError: true
              condition: succeededOrFailed()
